In [1]:
import numpy as np

In [2]:
t1 = np.arange(12)

In [3]:
t1.shape

(12,)

In [4]:
t2 = np.array([1,2,3],[4,5,6])

TypeError: data type not understood

In [5]:
t2 = np.array([1 2 3],[4 5 6])

SyntaxError: invalid syntax (<ipython-input-5-bd1a157cde75>, line 1)

In [6]:
t2 = np.array([[1,2,3],[4,5,6]])

In [7]:
t2.shape

(2, 3)

In [8]:
t1.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
t3 = np.arrange(24).reshape(2,3,4)

AttributeError: module 'numpy' has no attribute 'arrange'

In [10]:
t3 = np.arange(24).reshape(2,3,4)

In [11]:
t3.shape

(2, 3, 4)

In [12]:
t3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [13]:
t3.reshape((3,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [14]:
t3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [15]:
t3.reshape((24,))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [16]:
t2.reshape(t2.shape[0]*t2.shape[1],)

array([1, 2, 3, 4, 5, 6])

In [17]:
t2

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
t2.flatten

<function ndarray.flatten>

In [19]:
t2.flatten()

array([1, 2, 3, 4, 5, 6])

In [20]:
t2

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
t2+2

array([[3, 4, 5],
       [6, 7, 8]])

In [22]:
t2/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [23]:
t2/0

/home/fjyy/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf],
       [inf, inf, inf]])

In [24]:
t5

NameError: name 't5' is not defined

In [25]:
t3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [26]:
t3 = t3.reshape((4,6))

In [27]:
t3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [29]:
t4 = np.arange(100,124).reshape((4,6))

In [30]:
t4

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123]])

In [31]:
t3+t4

array([[100, 102, 104, 106, 108, 110],
       [112, 114, 116, 118, 120, 122],
       [124, 126, 128, 130, 132, 134],
       [136, 138, 140, 142, 144, 146]])

In [32]:
t5 = np.arange(0,6)

In [33]:
t5

array([0, 1, 2, 3, 4, 5])

In [34]:
t4-t5

array([[100, 100, 100, 100, 100, 100],
       [106, 106, 106, 106, 106, 106],
       [112, 112, 112, 112, 112, 112],
       [118, 118, 118, 118, 118, 118]])

In [36]:
t6 = np.arange(0,4).reshape(4,1)

In [37]:
t6

array([[0],
       [1],
       [2],
       [3]])

In [38]:
t4

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123]])

In [39]:
t6-t4

array([[-100, -101, -102, -103, -104, -105],
       [-105, -106, -107, -108, -109, -110],
       [-110, -111, -112, -113, -114, -115],
       [-115, -116, -117, -118, -119, -120]])

In [40]:
t7 = np.arange(0,10)

In [41]:
t7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
t4

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123]])

In [43]:
t4-t7

ValueError: operands could not be broadcast together with shapes (4,6) (10,) 

In [44]:
s1 = np.array([1,3,5],dtype="bool")

In [45]:
s1

array([ True,  True,  True])

In [46]:
s1.astype("int8")

array([1, 1, 1], dtype=int8)

In [47]:
import random as rn

In [50]:
s2 = np.array([rn.random() for i in range(10)])

In [51]:
s2

array([0.84270105, 0.05234005, 0.88223541, 0.33391731, 0.29280443,
       0.87058506, 0.5290154 , 0.74511549, 0.91975434, 0.41110134])

In [52]:
np.round(s2)

array([1., 0., 1., 0., 0., 1., 1., 1., 1., 0.])

In [53]:
np.round(s2,3)

array([0.843, 0.052, 0.882, 0.334, 0.293, 0.871, 0.529, 0.745, 0.92 ,
       0.411])

In [54]:
t11=np.arange(12).reshape(3,4).astype("float")

In [55]:
t11[1,2:] = np.nan

In [56]:
t11

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5., nan, nan],
       [ 8.,  9., 10., 11.]])

In [57]:
for i in range(t11.shape[1]):  #取每列
      temp_col = t1[:,i]    #当前一列
      nan_num = np.count_nonzero(temp_col!=temp_col)
      if nan_num!=0:
            temp_not_nan_col = temp_col[temp_col==temp_col]
            temp_col[np.isnan(temp_col)] = temp_not_nan_col.mean()

IndexError: too many indices for array

In [58]:
for i in range(t11.shape[1]):  #取每列
    temp_col = t1[:,i]    #当前一列
    nan_num = np.count_nonzero(temp_col!=temp_col)
    if nan_num!=0:
        temp_not_nan_col = temp_col[temp_col==temp_col]
        temp_col[np.isnan(temp_col)] = temp_not_nan_col.mean()

IndexError: too many indices for array

In [59]:
for i in range(t11.shape[1]):  #取每列
    temp_col = t11[:,i]    #当前一列
    nan_num = np.count_nonzero(temp_col!=temp_col)
    if nan_num!=0:
        temp_not_nan_col = temp_col[temp_col==temp_col]
        temp_col[np.isnan(temp_col)] = temp_not_nan_col.mean()

In [60]:
def fill_ndarray(t11):
    for i in range(t11.shape[1]):  #取每列
    temp_col = t11[:,i]    #当前一列
    nan_num = np.count_nonzero(temp_col!=temp_col)
    if nan_num!=0:
        temp_not_nan_col = temp_col[temp_col==temp_col]
        temp_col[np.isnan(temp_col)] = temp_not_nan_col.mean()
    return t11

IndentationError: expected an indented block (<ipython-input-60-4ad76a157ce8>, line 3)

In [61]:
print(t11)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
